#pragma once

#define TUNSAFE_VERSION_STRING "TunSafe 1.3-rc3"

#define WITH_HANDSHAKE_EXT 0
#define WITH_SHORT_HEADERS 0
#define WITH_HEADER_OBFUSCATION 0
#define WITH_AVX512_OPTIMIZATIONS 0
#define WITH_BENCHMARK 0
